import type { Vulnerability } from './Beacon/types';

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString().split('T')[0];
}

function daysAgoTimestamp(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(9 + (days % 8), (days * 17) % 60, (days * 7) % 60);
  return d.toISOString().replace('T', ' ').substring(0, 16);
}

export const mockVulnerabilities: Vulnerability[] = [
  // CID-01 (batch-1)
  {
    uuid: 'v1',
    vulnerabilityId: 'LWL-2026-4401',
    purl: 'pkg:maven/org.apache.logging.log4j/log4j-core@2.17.1',
    componentName: 'log4j-core',
    componentVersion: '2.17.1',
    publishedVersions: [],
    title: 'JNDI injection via crafted log message',
    cwe: 'CWE-917',
    description: 'Remote code execution through JNDI lookup in log messages',
    severity: 'Critical',
    cvss: 9.8,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    status: 'Submitted',
    ecosystem: 'java',
    submittedDate: daysAgo(2),
    lastUpdated: daysAgoTimestamp(1),
    ageDays: 2,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v2',
    vulnerabilityId: 'LWL-2026-4301',
    purl: 'pkg:pypi/django@4.1.0',
    componentName: 'Django',
    componentVersion: '4.1.0',
    publishedVersions: [],
    title: 'SQL injection in QuerySet.extra()',
    cwe: 'CWE-89',
    description: 'SQL injection through unsanitized extra() parameters',
    severity: 'Important',
    cvss: 8.6,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    status: 'Classified',
    ecosystem: 'python',
    submittedDate: daysAgo(7),
    lastUpdated: daysAgoTimestamp(4),
    ageDays: 7,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v3',
    vulnerabilityId: 'LWL-2026-4101',
    purl: 'pkg:maven/org.apache.commons/commons-text@1.9',
    componentName: 'Apache Commons Text',
    componentVersion: '1.9',
    publishedVersions: [],
    title: 'Text4Shell - StringSubstitutor interpolation',
    cwe: 'CWE-94',
    description: 'Code injection through uncontrolled string interpolation',
    severity: 'Moderate',
    cvss: 6.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    status: 'Validation',
    ecosystem: 'java',
    submittedDate: daysAgo(35),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 35,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },

  // CID-214 (batch-2)
  {
    uuid: 'v4',
    vulnerabilityId: 'LWL-2026-4201',
    purl: 'pkg:maven/org.apache.tomcat/tomcat-catalina@9.0.65',
    componentName: 'Tomcat Catalina',
    componentVersion: '9.0.65',
    publishedVersions: [],
    title: 'Request smuggling via chunked encoding',
    cwe: 'CWE-444',
    description: 'HTTP request smuggling through malformed chunked transfer encoding',
    severity: 'Critical',
    cvss: 8.1,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 1',
    status: 'Fix in Progress',
    ecosystem: 'java',
    submittedDate: daysAgo(15),
    lastUpdated: daysAgoTimestamp(3),
    ageDays: 15,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v5',
    vulnerabilityId: 'LWL-2026-4001',
    purl: 'pkg:maven/org.apache.shiro/shiro-core@1.10.0',
    componentName: 'Apache Shiro',
    componentVersion: '1.10.0',
    publishedVersions: ['1.10.1.rhlw-00002', '1.10.0.rhlw-00001'],
    title: 'Authentication bypass via path traversal',
    cwe: 'CWE-287',
    description: 'Auth bypass using path normalization inconsistencies',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N',
    exploitTested: true,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    status: 'Lightwell Network',
    ecosystem: 'java',
    submittedDate: daysAgo(35),
    lastUpdated: daysAgoTimestamp(2),
    ageDays: 35,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v6',
    vulnerabilityId: 'LWL-2026-4404',
    purl: 'pkg:pypi/requests@2.28.0',
    componentName: 'requests',
    componentVersion: '2.28.0',
    publishedVersions: [],
    title: 'SSRF via redirect handling',
    cwe: 'CWE-918',
    description: 'Server-side request forgery through unvalidated redirects',
    severity: 'Minor',
    cvss: 3.7,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 4',
    status: 'Submitted',
    ecosystem: 'python',
    submittedDate: daysAgo(1),
    lastUpdated: daysAgoTimestamp(0),
    ageDays: 1,
    duplicate: true,
    duplicateOf: 'LWL-2026-4027',
    ltwlsupt_ticket_id: 'batch-2',
  },

  // Closed without remediation
  {
    uuid: 'v7',
    vulnerabilityId: 'LWL-2026-4501',
    purl: 'pkg:npm/lodash@4.17.20',
    componentName: 'lodash',
    componentVersion: '4.17.20',
    publishedVersions: [],
    title: 'Prototype pollution in zipObjectDeep',
    cwe: 'CWE-1321',
    description: 'Prototype pollution through crafted object paths',
    severity: 'Moderate',
    cvss: 5.6,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:L/A:L',
    exploitTested: false,
    reproducerIncluded: true,
    customerPriority: 'Priority 3',
    status: "Won't Do",
    resolutionReason: 'Upstream already rejected a similar patch; remediating would fork the package indefinitely.',
    ecosystem: 'javascript',
    submittedDate: daysAgo(40),
    lastUpdated: daysAgoTimestamp(5),
    ageDays: 40,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v8',
    vulnerabilityId: 'LWL-2026-4502',
    purl: 'pkg:maven/com.fasterxml.jackson.core/jackson-databind@2.13.0',
    componentName: 'jackson-databind',
    componentVersion: '2.13.0',
    publishedVersions: [],
    title: 'Reported deserialization gadget chain',
    cwe: 'CWE-502',
    description: 'Alleged unsafe deserialization in default typing mode',
    severity: 'Important',
    cvss: 7.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H',
    exploitTested: true,
    reproducerIncluded: true,
    customerPriority: 'Priority 2',
    status: 'Not a Bug',
    resolutionReason: 'Default typing is disabled in the customer configuration; no exploitable path was found.',
    ecosystem: 'java',
    submittedDate: daysAgo(28),
    lastUpdated: daysAgoTimestamp(6),
    ageDays: 28,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
  {
    uuid: 'v9',
    vulnerabilityId: 'LWL-2026-4503',
    purl: 'pkg:pypi/urllib3@1.26.12',
    componentName: 'urllib3',
    componentVersion: '1.26.12',
    publishedVersions: [],
    title: 'TLS verification bypass under rare redirect conditions',
    cwe: 'CWE-295',
    description: 'Certificate validation allegedly skipped after certain redirects',
    severity: 'Important',
    cvss: 7.4,
    cvssVector: 'CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 2',
    status: 'Cannot Reproduce',
    resolutionReason: 'Unable to reproduce with the provided reproducer and package version.',
    ecosystem: 'python',
    submittedDate: daysAgo(22),
    lastUpdated: daysAgoTimestamp(8),
    ageDays: 22,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-1',
  },
  {
    uuid: 'v10',
    vulnerabilityId: 'LWL-2026-4504',
    purl: 'pkg:nuget/Newtonsoft.Json@12.0.3',
    componentName: 'Newtonsoft.Json',
    componentVersion: '12.0.3',
    publishedVersions: [],
    title: 'Insecure deserialization in legacy TypeNameHandling usage',
    cwe: 'CWE-502',
    description: 'Deserialization risk when TypeNameHandling is enabled',
    severity: 'Moderate',
    cvss: 6.5,
    cvssVector: 'CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N',
    exploitTested: false,
    reproducerIncluded: false,
    customerPriority: 'Priority 3',
    status: 'Obsolete',
    resolutionReason: 'Customer migrated off the affected package version after intake.',
    ecosystem: 'csharp',
    submittedDate: daysAgo(60),
    lastUpdated: daysAgoTimestamp(10),
    ageDays: 60,
    duplicate: false,
    ltwlsupt_ticket_id: 'batch-2',
  },
];
